version: '3'

services:
	spark:
		image: docker.io/bitnami/spark:3
		container_name: spark-main
		environment: 
			- SPARK_MODE=master
			- SPARK_RPC_AUTHENTICATION_ENABLED=no
			- SPARK_RPC_ENCRYPTION_ENABLED=no
			- SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
			- SPARK_SSL_ENABLED=no
			- SPARK_DAEMON_USER=ubuntu
			- SPARK_DAEMON_GROUP=ubuntu
		ports:
			- '8080:8080'
			- '7077:7077'
		volumes:
			- ./apps:/opt/spark-apps
			- ./data:/opt/spark-data
	spark-worker:
		image: docker.io/bitnami/spark:3
		environment:
			- SPARK_MODE=worker
			- SPARK_MASTER_URL=spark://spark:7077
			- SPARK_WORKER_MEMORY=1G
			- SPARK_WORKER_CORES=1
			- SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
			- SPARK_SSL_ENABLED=no
			- SPARK_DAEMON_USER=ubuntu
			- SPARK_DAEMON_GROUP=ubuntu
		ports:
			- '8081-8089:8081'
		volumes:
			- ./apps:/opt/spark-apps
			- ./data:/opt/spark-data
	docker-remote:
		image: jarkt/docker-remote-api
		ports:
			-'2375:2375'
		volumes:
			- /var/run/docker.sock:/var/run/docker.sock